version: "3.8"

networks:
  ppgti-rabbitmq:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ppgti
      RABBITMQ_DEFAULT_PASS: ppgti
      RABBITMQ_DEFAULT_VHOST: ppgti_host
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
      - ./rabbitmq/log:/var/log/rabbitmq
    networks:
      - ppgti-rabbitmq
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
      
  expo:
    build:
      context: ./cafenamesa-cliente
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./cafenamesa-cliente:/opt/cafenamesa-cliente:delegated
      - ./cafenamesa-cliente/package.json:/opt/cafenamesa-cliente/package.json
      - notused:/opt/cafenamesa-cliente/node_modules
    healthcheck:
      disable: true

  app:
    build: ./cafenamesa-ordering
    container_name: ordering
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./cafenamesa-ordering:/usr/app
    networks:
      - ppgti-rabbitmq
      
volumes:
  notused: